all.tabs <- data.frame(pos = c(1,2,2.1,2.2,2.3,2.4,2.5,3,4,5,6),
                       tabName = c("panelIdInformation",
                                   "panelIdData",
                                   "panelSubIdxlsx",
                                   "panelSubIdcsv",
                                   "john",
                                   "RDatabase",
                                   "panelSubIdRNG",
                                   "panelIdDefine2",
                                   "panelIdExplore2",
                                   "panelIdOverview",
                                   "panelIdEvaluation"),
                       label = c("0. Information",
                                 "1. Get data",
                                 ".xlsx",
                                 ".csv",
                                 "(placeholder) Johns-dataSet",
                                 "from R database",
                                 "generate Dataset",
                                 "2a. Define/Redefine datatypes",
                                 "3a. Explore",
                                 "4. Overview",
                                 "5. Evaluation"),
                       icon = c("info",
                                "file-import",
                                "file-excel",
                                "file-alt",
                                "blind",
                                "th",
                                "dice",
                                "keyboard",
                                "search",
                                "eye",
                                "file-upload"))